Add field validation
kamabzalov/admss-crm pull request #216
Opened 2023-11-21 07:45 UTC by JSDID

2023-11-21 14:14 UTC, kamabzalov reviewed
Из изменений я вижу только новые стили/классы. Достаточно ли этого?

2023-11-21 14:16 UTC, JSDID commented
> Из изменений я вижу только новые стили/классы. Достаточно ли этого?

да

2023-11-21 14:19 UTC, JSDID commented
да

2023-11-22 13:35 UTC, kamabzalov requested changes
Был добавлен новый метод для валидации юзера

2023-11-22 13:46 UTC, kamabzalov approved these changes

2023-11-22 13:46 UTC, merged