Add to user context menu
kamabzalov/admss-crm pull request #258
Opened 2024-04-28 16:42 UTC by JSDID

2024-04-28 16:43 UTC, JSDID commented
Не работает. Запрос уходит, возвращает ОК, но локация все равно остается одна.

![photo_2024-04-28_19-37-24](https://github.com/kamabzalov/admss-crm/assets/102165823/b3375983-e6b4-426a-8d27-eb86d091deda)
![photo_2024-04-28_19-37-00](https://github.com/kamabzalov/admss-crm/assets/102165823/11bc8214-e5f9-4601-bf24-e1e5d236dc37)
![photo_2024-04-28_19-37-15](https://github.com/kamabzalov/admss-crm/assets/102165823/422751df-0072-4b27-9854-863758a1db77)

2024-04-29 09:49 UTC, kamabzalov reviewed
Посмотрите в swagger описание метода

2024-04-30 07:11 UTC, JSDID commented
При перечитывании все равно одна локация
 
![photo_2024-04-30_10-09-10](https://github.com/kamabzalov/admss-crm/assets/102165823/aadf0252-62cd-4b16-9768-fcac6848bbdc)
![photo_2024-04-30_10-05-49](https://github.com/kamabzalov/admss-crm/assets/102165823/66a01772-d1ba-41a4-8d24-3ec3f159545a)
![photo_2024-04-30_10-09-10 (2)](https://github.com/kamabzalov/admss-crm/assets/102165823/5659ead8-fb6b-4bd5-97f7-d306b36a4313)

2024-04-30 07:18 UTC, JSDID commented
![photo_2024-04-30_10-05-49](https://github.com/kamabzalov/admss-crm/assets/102165823/54b6babb-665d-407e-9d52-57702dab480b)

2024-04-30 07:19 UTC, JSDID commented
при перечитывании все равно одна локация
![photo_2024-04-30_10-09-14](https://github.com/kamabzalov/admss-crm/assets/102165823/0f7e1778-14e2-4e88-93f5-2c37fbb55279)

2024-04-30 07:20 UTC, JSDID commented
![photo_2024-04-30_10-09-10](https://github.com/kamabzalov/admss-crm/assets/102165823/6d60e2e4-cd3a-4ed4-9a2d-56fcf650fb2c)

2024-04-30 11:55 UTC, kamabzalov commented
@JSDID сделайте задачу как следует!!!!

2024-05-01 08:38 UTC, kamabzalov commented
@JSDID почему отправляются пустые данные???? В третий раз повторяю - сделайте задачу как следует!!!
Последнее предупреждение - далее штраф

2024-05-01 17:51 UTC, kamabzalov reviewed
@JSDID 
![image](https://github.com/kamabzalov/admss-crm/assets/49127222/a4ac604f-0fbd-4429-be48-8f131ef97256)

2024-05-02 17:17 UTC, kamabzalov requested changes
1. Запрашивайте ревью
2. Кнопка неактивна

В след раз штраф

2024-05-03 16:12 UTC, kamabzalov reviewed
@JSDID бэк сделал новый endpoint для добавления одной инвентории - /api/v1/user/{id}/location
в swagger есть

2024-05-04 14:07 UTC, kamabzalov reviewed
@JSDID попробуйте оставить только те поля, которые есть в форме. То есть, например, поле status, error, info тут лишние (может сваггер криво обновлен)

2024-05-06 07:40 UTC, kamabzalov commented on src/services/user.service.ts
> +        //TODO: add error handler
Добавить показ snackbar

2024-05-06 17:48 UTC, kamabzalov requested changes

2024-05-06 17:48 UTC, kamabzalov commented on src/components/dashboard/users/table/columns/_columns.tsx
> +// @ts-nocheck
Зачем это тут?

2024-05-06 17:48 UTC, kamabzalov commented on src/services/user.service.ts
> +    } catch (error: unknown) {
А зачем catch и еще блок else с обработкой ошибки?

2024-05-06 17:50 UTC, kamabzalov commented on src/common/interfaces/UserData.tsx
> -    creatorusername?: string;
Почему удалено?

2024-05-07 04:28 UTC, JSDID commented on src/services/user.service.ts
> +    } catch (error: unknown) {
потому что у нас с бека ошибки приходят со статус кодом 200, которые и нужно кидать принудительно в catch, который уже и вернет ошибки (или сетевые, или бековские)

2024-05-07 04:29 UTC, JSDID commented on src/components/dashboard/users/table/columns/_columns.tsx
> +// @ts-nocheck
Это из-за этого падал Билд

2024-05-07 06:00 UTC, kamabzalov commented on src/components/dashboard/users/table/columns/_columns.tsx
> +// @ts-nocheck
Раньше это строки не было. И все было в порядке. Вы просто добавили, чтобы ts игнорировал этот файл. Это подгон под ответ. Убрать и разобраться

2024-05-07 11:46 UTC, kamabzalov approved these changes

2024-05-07 11:46 UTC, merged